 # schema.yml

 version: 2

 sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: id of orders
           - name: pdt_id
             description: id of product
           - name: revenue
             description: revenue of purchase
           - name: quantity
             description: quantity of product
        tests:
          - unique:
            column_name: "(orders_id ||'-'|| pdt_id )"
         
      - name: product
        identifier: raw_gz_product 
        description: products of Greenweez
        columns:
           - name: products_id
             description: id of product
           - name: purchse_price
             description: price of purchase
        tests:
          - unique:
             column_name: products_id
      
      - name: ship
        identifier: raw_gz_ship
        description: shipping of orders of Greenweez
        columns:
           - name: orders_id
             description: id of orders
           - name: shipping_fee
             description: shipping fee per order
           - name: logcost
             description: logcost per order
           - name: ship_cost
             description: shipping cost per order
        tests:
          - unique:
             column_name: orders_id
     