 # schema.yml

 version: 2

 sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: id of orders
           - name: pdt_id
             description: id of product
           - name: revenue
             description: revenue of purchase
           - name: quantity
             description: quantity of product
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id )"
      - name: product
        identifier: raw_gz_product 
        description: products of Greenweez
        columns:
           - name: products_id
             description: id of product
           - name: purchse_price
             description: price of purchase
        tests:
          - unique:
             column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: shipping of orders of Greenweez
        columns:
           - name: orders_id
             description: id of orders
           - name: shipping_fee
             description: shipping fee per order
           - name: logcost
             description: logcost per order
           - name: ship_cost
             description: shipping cost per order
        tests:
          - unique:
             column_name: orders_id
 models:
  - name: int_orders_margin
    description: Table with calculated margin and purchase cost per order
    columns:
      - name: orders_id
        description: Unique identifier of the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: Date of the order
        tests:
          - not_null
      - name: revenue
        description: Total revenue of the order
        tests:
          - not_null
      - name: quantity
        description: Total quantity of products in the order
        tests:
          - not_null
      - name: purchase_cost
        description: Total purchase cost of products in the order
        tests:
          - not_null
      - name: margin
        description: Revenue minus purchase cost
        tests:
          - not_null

  - name: int_orders_operational
    description: Table with operational margin per order
    columns:
      - name: orders_id
        description: Unique identifier of the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: Date of the order
        tests:
          - not_null
      - name: operational_margin
        description: Operational margin of the order
        tests:
          - not_null

  - name: finance_days
    description: Daily aggregated financial data for finance team
    columns:
      - name: date_date
        description: Date of the transactions
        tests:
          - not_null
          - unique
      - name: nb_transactions
        description: Number of distinct transactions on the day
        tests:
          - not_null
      - name: revenue
        description: Total revenue of the day
        tests:
          - not_null
      - name: average_basket
        description: Average revenue per order
        tests:
          - not_null
      - name: margin
        description: Total margin of the day
        tests:
          - not_null
      - name: operational_margin
        description: Total operational margin of the day
        tests:
          - not_null
