 # schema.yml

 version: 2

 sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from greenweez
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: id of orders
           - name: pdt_id
             description: id of product
           - name: revenue
             description: revenue of purchase
           - name: quantity
             description: quantity of product
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id )"
      - name: product
        identifier: raw_gz_product 
        description: products of Greenweez
        columns:
           - name: products_id
             description: id of product
           - name: purchse_price
             description: price of purchase
        tests:
          - unique:
             column_name: products_id
      - name: ship
        identifier: raw_gz_ship
        description: shipping of orders of Greenweez
        columns:
           - name: orders_id
             description: id of orders
           - name: shipping_fee
             description: shipping fee per order
           - name: logcost
             description: logcost per order
           - name: ship_cost
             description: shipping cost per order
        tests:
          - unique:
             column_name: orders_id
      - name: adwords
        identifier: raw_gz_adwords
        description: ad campaign of Greenweez runs in adwords 
        columns:
           - name: date_date
             description: date of ad campaign
           - name: paid_source
             description: source of campaign
           - name: campaign_key
             description: key of campaign
           - name: camPGN_name
             description: name of campaign
           - name: ads_cost
             description: cost of ads
           - name: impression
             description: number of impressions
           - name: click
             description: number of clicks
      - name: bing
        identifier: raw_gz_bing
        description: ad campaign of Greenweez runs in bing 
        columns:
           - name: date_date
             description: date of ad campaign
           - name: paid_source
             description: source of campaign
           - name: campaign_key
             description: key of campaign
           - name: camPGN_name
             description: name of campaign
           - name: ads_cost
             description: cost of ads
           - name: impression
             description: number of impressions
           - name: click
             description: number of clicks 
      - name: criteo
        identifier: raw_gz_criteo
        description: ad campaign of Greenweez runs in criteo 
        columns:
           - name: date_date
             description: date of ad campaign
           - name: paid_source
             description: source of campaign
           - name: campaign_key
             description: key of campaign
           - name: camPGN_name
             description: name of campaign
           - name: ads_cost
             description: cost of ads
           - name: impression
             description: number of impressions
           - name: click
             description: number of clicks 
      - name: facebook
        identifier: raw_gz_facebook
        description: ad campaign of Greenweez runs in facebook 
        columns:
           - name: date_date
             description: date of ad campaign
           - name: paid_source
             description: source of campaign
           - name: campaign_key
             description: key of campaign
           - name: camPGN_name
             description: name of campaign
           - name: ads_cost
             description: cost of ads
           - name: impression
             description: number of impressions
           - name: click
             description: number of clicks
 models:
  - name: int_orders_margin
    description: Table with calculated margin and purchase cost per order
    columns:
      - name: orders_id
        description: Unique identifier of the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: Date of the order
        tests:
          - not_null
      - name: revenue
        description: Total revenue of the order
        tests:
          - not_null
      - name: quantity
        description: Total quantity of products in the order
        tests:
          - not_null
      - name: purchase_cost
        description: Total purchase cost of products in the order
        tests:
          - not_null
      - name: margin
        description: Revenue minus purchase cost
        tests:
          - not_null

  - name: int_orders_operational
    description: Table with operational margin per order
    columns:
      - name: orders_id
        description: Unique identifier of the order
        tests:
          - not_null
          - unique
      - name: date_date
        description: Date of the order
        tests:
          - not_null
      - name: operational_margin
        description: Operational margin of the order
        tests:
          - not_null

  - name: finance_days
    description: Daily aggregated financial data for finance team
    columns:
      - name: date_date
        description: Date of the transactions
        tests:
          - not_null
          - unique
      - name: nb_transactions
        description: Number of distinct transactions on the day
        tests:
          - not_null
      - name: revenue
        description: Total revenue of the day
        tests:
          - not_null
      - name: average_basket
        description: Average revenue per order
        tests:
          - not_null
      - name: margin
        description: Total margin of the day
        tests:
          - not_null
      - name: operational_margin
        description: Total operational margin of the day
        tests:
          - not_null
  - name: int_campaigns
    description: Table with ad campaigns
    columns:
      - name: date_date
        description: date of campaign
        tests:
          - not_null
      - name: paid_source
        description: source of campaign
        tests:
          - not_null
      - name: campaign_key
        description: key of campaign
        tests:
          - not_null
      - name: campaign_name
        description: name of campaign
        tests:
          - not_null
      - name: ads_cost
        description: cost of ads
        tests:
          - not_null
      - name: impression
        description: number of impressions
        tests:
          - not_null
      - name: click
        description: number of clicks
        tests:
          - not_null
    tests:
          - unique:
              column_name: "(date_date || '-' || campaign_key )"
  - name: int_campaigns_day
    description: Daily aggregated campaings performance
    columns:
      - name: date_date
        description: date of campaigns
        tests:
          - not_null
          - unique
      - name: ads_cost
        description: total cost
        tests:
          - not_null
      - name: ads_impression
        description: total impression
        tests:
          - not_null
      - name: ads_clicks
        description: total clicks
        tests:
          - not_null
  - name: finance_campaigns_day
    description: Financial and  campaings KPIs per day
    columns:
      - name: date_date
        description: Date of the transactions
        tests:
          - not_null
          - unique
      - name: ads_margin
        description: Total margin of ads
        tests:
          - unique
      - name: average_basket
        description: Average revenue per order
        tests:
          - not_null
      - name: operational_margin
        description: Total operational margin of the day
        tests:
          - not_null
      - name: ads_cost
        description: total cost
        tests:
          - not_null
      - name: ads_impression
        description: total impression
        tests:
          - not_null
      - name: ads_clicks
        description: total clicks
        tests:
          - not_null
      - name: quantity
        description: Number of products
        tests:
          - not_null
      - name: revenue
        description: Total revenue of the day
        tests:
          - not_null
      - name: purchase_cost
        description: Total cost of purchases of the day
        tests:
          - not_null
      - name: margin
        description: Total margin of the day
        tests:
          - not_null
      - name: shipping_fee
        description: Total shipping fees of the day
        tests:
          - not_null
      - name: logcost
        description: Total logcost of the day
        tests:
          - not_null

        